# Generated by Django 3.0.3 on 2020-02-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=6)),
                ('topic', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=500)),
                ('progress', models.CharField(default='в процессе', max_length=100)),
            ],
        ),
    ]
