# Generated by Django 3.0.3 on 2020-02-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255, verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('topic', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=500)),
                ('progress', models.CharField(default='', max_length=100)),
                ('is_active', models.CharField(choices=[(1, 'Accept'), (2, 'Reject'), (3, 'Renew'), (4, 'completely rejected')], max_length=10)),
                ('cause', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
