# Generated by Django 3.0.3 on 2020-02-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomment',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newcomments', to='application_system.Statement'),
        ),
    ]
