# Generated by Django 3.0.3 on 2020-02-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_system', '0002_auto_20200206_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='progress',
            field=models.CharField(default='', max_length=100),
        ),
    ]
