# Generated by Django 3.0.3 on 2020-02-17 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_system', '0002_auto_20200213_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcomment',
            name='comments',
        ),
        migrations.AddField(
            model_name='newcomment',
            name='statements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application_system.Statement'),
        ),
        migrations.AlterField(
            model_name='newcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
