# Generated by Django 3.0.3 on 2020-02-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_system', '0002_auto_20200226_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='cause',
        ),
    ]
