# Generated by Django 3.0.3 on 2020-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_system', '0003_auto_20200217_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='cause',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
