# Generated by Django 3.0.3 on 2020-02-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_system', '0003_auto_20200207_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
