# Generated by Django 3.0.3 on 2020-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_system', '0004_decision_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
    ]
