# Generated by Django 3.0.3 on 2020-02-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_system', '0005_auto_20200210_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renew', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application_system.Decision')),
            ],
        ),
    ]
