# Generated by Django 3.0.3 on 2020-02-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_system', '0006_renewstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='is_active',
            field=models.CharField(choices=[(1, 'Accept'), (2, 'Reject'), (3, 'Renew'), (4, 'completely rejected')], max_length=10),
        ),
        migrations.DeleteModel(
            name='RenewStatement',
        ),
    ]
