# Generated by Django 3.0.2 on 2020-01-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='return_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='shop.Purchase'),
        ),
    ]
