# Generated by Django 3.0.2 on 2020-01-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200122_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='return_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Purchase'),
        ),
    ]
