# Generated by Django 3.0.2 on 2020-01-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200126_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnproduct',
            options={'ordering': ['request_time']},
        ),
    ]
