# Generated by Django 3.0.3 on 2020-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sex',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default=None, max_length=10),
        ),
    ]
