# Generated by Django 3.0.3 on 2020-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_myuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=10, null=True),
        ),
    ]
